version: "3"

services:
  redis:
    container_name: "redis"
    image: "redis"
    command: redis-server --requirepass ${REDIS_PASSWORD}  
    ports:
      - "6379:6379"
    networks:
      - manager_cert
    env_file:
      - ./cert-app/.env
    

  python:
    container_name: "backend"
    build:
      context: ./cert-app/
      dockerfile: Dockerfile
    ports: 
      - "8081:8081"
    networks:
      - manager_cert
    depends_on:
      - redis
    env_file:
      - ./cert-app/.env
    volumes:
      - ./cert-app/logs:/app/cert-app/logs

networks:
  manager_cert:

# volumes:
#   postgres-vol: